name: Auto Update from Upstream

on:
  schedule:
    # 每天下午6点运行 (UTC+8)
    - cron: '0 10 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: # 明确设置权限
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/blackmatrix7/ios_rule_script.git
          
      - name: Fetch and Merge Upstream
        run: |
          git fetch upstream master --depth=1
          # 在合并之前备份自定义文件到临时目录（不在 .github/workflows 内）
          mkdir -p /tmp/custom_backup
          cp -r .github/workflows/* /tmp/custom_backup/
          git merge upstream/master --allow-unrelated-histories --no-edit
          # 恢复自定义文件
          cp -r /tmp/custom_backup/* .github/workflows/
          rm -rf /tmp/custom_backup
          
      - name: Push Changes
        run: |
          git add .
          git commit -m "chore: sync upstream and restore custom workflows" || echo "No changes to commit"
          git push origin master
