name: Generate IP Lists

on:
  repository_dispatch:
    types: [generate_ip]

jobs:
  generate-lists:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout meta-rules-dat repository
        uses: actions/checkout@v4
        with:
          repository: rdone4425/meta-rules-dat
          ref: meta
          path: meta-rules-dat

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate IP Lists
        run: |
          python3 << EOF
          import os
          import json
          
          # 获取传入的国家代码
          country_code = '${{ github.event.client_payload.country }}'.lower()
          
          # 创建输出目录
          os.makedirs(f'ip-lists/{country_code}', exist_ok=True)
          
          # 读取并处理 IPv4 列表
          ipv4_file = f'./meta-rules-dat/geo/geoip/{country_code}.list'
          if os.path.exists(ipv4_file):
              with open(ipv4_file, 'r') as f:
                  ipv4_list = [line.strip() for line in f if line.strip()]
              
              # 保存 IPv4 列表
              with open(f'ip-lists/{country_code}/ipv4.txt', 'w') as f:
                  f.write('\n'.join(ipv4_list))
          
          # 读取并处理 IPv6 列表
          ipv6_file = f'./meta-rules-dat/geo/geoip6/{country_code}.list'
          if os.path.exists(ipv6_file):
              with open(ipv6_file, 'r') as f:
                  ipv6_list = [line.strip() for line in f if line.strip()]
              
              # 保存 IPv6 列表
              with open(f'ip-lists/{country_code}/ipv6.txt', 'w') as f:
                  f.write('\n'.join(ipv6_list))
          
          # 生成元数据文件
          metadata = {
              "country_code": country_code,
              "has_ipv4": os.path.exists(ipv4_file),
              "has_ipv6": os.path.exists(ipv6_file),
              "generated_at": "${{ github.event.client_payload.timestamp }}"
          }
          
          with open(f'ip-lists/{country_code}/metadata.json', 'w') as f:
              json.dump(metadata, f, indent=2)
          EOF

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ip-lists/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update IP lists for ${{ github.event.client_payload.country }}" && git push) 
