name: Update Loon Rules Directory

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyYAML
        
    - name: Create update script
      run: |
        cat > update_directory.py << 'EOF'
        import requests
        import yaml
        from datetime import datetime
        import os

        def update_directories():
            # GitHub API URL
            api_url = "https://api.github.com/repos/rdone4425/ios_rule_script/contents/rule/Loon"
            headers = {
                'Accept': 'application/vnd.github.v3+json',
            }
            
            try:
                # 发送API请求
                response = requests.get(api_url, headers=headers)
                response.raise_for_status()
                contents = response.json()
                
                # 获取目录列表
                directories = [item['name'] for item in contents if item['type'] == 'dir']
                directories.sort()  # 按字母顺序排序
                
                # 创建ios_rule_script目录（如果不存在）
                if not os.path.exists('ios_rule_script'):
                    os.makedirs('ios_rule_script')
                
                # 将目录名写入loon.txt
                with open('ios_rule_script/loon.txt', 'w', encoding='utf-8') as f:
                    for directory in directories:
                        f.write(f"{directory}\n")
                
                # 同时创建YAML格式的文件
                data = {
                    'metadata': {
                        'updated': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                        'source': 'rdone4425/ios_rule_script',
                        'total_directories': len(directories)
                    },
                    'directories': directories
                }
                
                with open('ios_rule_script/loon.yml', 'w', encoding='utf-8') as f:
                    yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False)
                
                return True
                
            except Exception as e:
                print(f"Error: {e}")
                return False
        
        if __name__ == "__main__":
            success = update_directories()
            exit(0 if success else 1)
        EOF
        
    - name: Run update script
      run: python update_directory.py
        
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add ios_rule_script/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Loon rules directory $(date '+%Y-%m-%d %H:%M:%S')" && git push) 
